### ISSUE TITLE
default labels

### ISSUE THREAD

**Issue by lucacioria** [buildo/github-prettifier#3]
## requirements
- check the presence of all default labels (as described here https://github.com/buildo/infra/blob/master/readmes/github-labels.md) and create those missing
- fix colors on labels already present
- use a consistent color set across all projects
- not delete any other label present

## specs
- where should we encore colors / labels? maybe we can have a GH repo that serves as master and the script simply copies labels from that one? (pro: easy to evolve without need to redeploy GH prettifier)

**Comment by gabro** [comment]
Done (see #4). Labels definitions are taken from an external url (defined in config).

For our purposes labels are taken from a `github-labels.json` file stored on buildo/infra.

The definition file has this structure:

```json
[{
  "name": "api",
  "color": "f4f4f4"
}, {
  "name": "iOS",
  "color": "ccc",
  "whitelist": [
    "awesome-app"
  ]
}]
```

where

- `name`: the name of the label
- `color`: the color of the label
- `whitelist`: if present, applies the label only to the listed repos. If missing, applies to all.

No labels are ever removed (it's an irreversible operation, as it implicitly removes all the labels from all the issues). Labels are created if necessary and updated otherwise.
